/**
 * Supabase database type stub.
 *
 * In production, this would be generated by the Supabase CLI:
 *   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/db/schema/types.ts
 *
 * Until the Supabase project is live and the schema is applied, this provides
 * a minimal type stub that keeps TypeScript happy while preserving type safety.
 *
 * The Database generic type is used by Supabase clients to type query results.
 * When the real types are generated, replace this file entirely.
 */
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: {
      store_integration_credential: {
        Args: {
          p_secret: string
          p_name: string
          p_description: string | null
        }
        Returns: string
      }
      get_integration_credential: {
        Args: {
          p_secret_id: string
        }
        Returns: string
      }
      custom_access_token_hook: {
        Args: {
          event: Record<string, unknown>
        }
        Returns: Record<string, unknown>
      }
    }
    Enums: {
      plan_tier: 'starter' | 'professional' | 'agency' | 'enterprise'
      org_role: 'owner' | 'admin' | 'member' | 'viewer'
      sync_status: 'pending' | 'running' | 'succeeded' | 'failed' | 'retrying'
    }
    CompositeTypes: Record<string, never>
  }
}
